### ISSUE TITLE
bids_convert crashing

### ISSUE THREAD

**Issue by egarza** [BrkRaw/bruker#11]
Hi!

I'm testing the bids_convert with my data.

First I ran the bids_helper to create the XLSX and JSON files.

Then I edited the [xlsx file](https://drive.google.com/file/d/1p1KOf1ma61PLnG2eGb-8l98WwgtMBejg/view?usp=sharing).
Here is the [JSON](https://drive.google.com/file/d/1tNqAhjouxS0K9ZpiDqeBZCXeDFYwMsi7/view?usp=sharing)

Then I ran:

`brkraw bids_convert -j Model20p_bids.json -o Model20p_bids --ignore-rescale Model20p Model20p_bids.xlsx`

I get this error crash:

```
Traceback (most recent call last):
  File "/home/egarza/.local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'SessID'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/egarza/.local/bin/brkraw", line 11, in <module>
    load_entry_point('bruker==0.3.3', 'console_scripts', 'brkraw')()
  File "/home/egarza/.local/lib/python3.6/site-packages/brkraw/scripts/brkraw.py", line 362, in main
    if all(pd.isnull(df['SessID'])):
  File "/home/egarza/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/egarza/.local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'SessID'
```

Is it because `SessID` is not numeric?

Thanks,

Eduardo

**Comment by egarza** [comment]
I ran everything again with the "default" `SessID` and it worked. 

Can SessID be modified such as SubjectID?

Otherwise, it worked great.

Thank you

Eduardo

**Comment by egarza** [comment]
In the JSON, `"TaskName": "Value was not specified"`, however I did put `rest` as the task in the XLSX.

**Comment by dvm-shlee** [comment]
@egarza could you send me the xlsx file showing the issue?

**Comment by egarza** [comment]
It's in my comment. It's a Google drive

**Comment by dvm-shlee** [comment]
@egarza According to the error message you posted, it seems the pandas do not recognize the 'SessID' column. So wondering if the file you put a link on your commend is the file that causing the error or with the default session?

Thanks!

**Comment by dvm-shlee** [comment]
@egarza Regarding the JSON, The "Value was not specified" message will be added when it is assigned as null at the JSON file, and unfortunately, the JSON does not communicate with BIDS sheets, so you need to provide the value for the TaskName by editing the JSON file.

This means that if you have multiple tasks design, it requires manual updates for single file.
I'm considering making an additional tool to handle that since it is really hard to implement on the conversion step without the user input, but if you have any suggestions (such as using task field value to implant JSON is enough) I could implement that.

Thank you!

**Comment by egarza** [comment]
The file I uploaded was the one that DID NOT work. I can upload the file that DID work. I just left the `SessID`alone, no changes on the column name. I'll upload the working file in a moment.

About the JSON, if the task field from the XLSX can be sent to the JSON that would help a lot, otherwise changing eaach individual JSON can become challenging.

Thanks

**Comment by dvm-shlee** [comment]
@egarza BTW, regarding the JSON, I meant you only need changing 'Model20p_bids.json' file instead of all other files, but this option only allows one task per dataset.

Because the value in 'task' in the filename seems not sufficient to use as task value, I'm considering other options, such as combine with task_event file, which researcher required to upload for task-based fMRI, so be more flexible with multiple task design.

If you only have resting-state data at this point, please fill out the 'TaskName' field in Model20p_bids.json such as 'resting state'. It would create the JSON for all single files with the given value. I hope this works for you.

**Comment by dvm-shlee** [comment]
@egarza Regarding the BIDS sheet, the error caused because the BIDS sheet is not the first datasheet in excel.

Please check the below image.
![image](https://user-images.githubusercontent.com/7221078/84218078-b9ad0c00-aa9b-11ea-9363-37941a426725.png)

If you change the above as below, it will work again.
![image](https://user-images.githubusercontent.com/7221078/84218145-d3e6ea00-aa9b-11ea-94e3-aeb1a7b11f7d.png)

I hope this can resolve your problem.
Thank you!
