### ISSUE TITLE
brkraw tonii_all fails while tonii succeeds

### ISSUE THREAD

**Issue by gdevenyi** [BrkRaw/bruker#2]
```
$ brkraw --version
brkraw v0.3.3rc1
$ python --version
Python 3.7.6
$ brkraw info raw/
Paravision 5.1
--------------
UserAccount:    galdan
Date:           2020-01-31
Researcher:     MCH_DEV_PHT_001
Subject ID:     20200131_MCH_DEV_PHT_001
Session ID:     dev
Study ID:       1
Date of Birth:  None
Sex:            male
Weight:         5 kg
Subject Type:   Human
Position:       Supine          Entry:  HeadFirst

[ScanID]        Sequence::Protocol::[Parameters]
[001]   FLASH (pvm)::01-TriPilot-multi::
        [ TR: 200 ms, TE: 3 ms, pixelBW: 500.80 Hz, FlipAngle: 30 degree]
    [01] dim: 2D, matrix_size: 256 x 256 x 15, fov_size: 40 x 40 (unit:mm)
         spatial_resol: 0.156 x 0.156 x 1.000 (unit:mm), temporal_resol: 25600.000 (unit:msec)
[002]   FLASH (pvm)::exvivoDanFLASH::
        [ TR: 21.47 ms, TE: 5.11 ms, pixelBW: 96.90 Hz, FlipAngle: 20 degree]
    [01] dim: 3D, matrix_size: 228 x 258 x 130, fov_size: 15.96 x 18.06 x 9.1 (unit:mm)
         spatial_resol: 0.070 x 0.070 x 0.070 (unit:mm), temporal_resol: 1920266.000 (unit:msec)
$ brkraw tonii raw/
NifTi file is genetared... [20200131_MCH_DEV_PHT_001_1-01-1]
NifTi file is genetared... [20200131_MCH_DEV_PHT_001_1-02-1]
$ brkraw tonii_all raw/
Traceback (most recent call last):
  File "/home/gdevenyi/miniforge3/bin/brkraw", line 8, in <module>
    sys.exit(main())
  File "/home/gdevenyi/miniforge3/lib/python3.7/site-packages/brkraw/scripts/brkraw.py", line 143, in main
    study = BrukerLoader(sub_path)
  File "/home/gdevenyi/miniforge3/lib/python3.7/site-packages/brkraw/lib/loader.py", line 88, in __init__
    self._pvobj = load(path)
  File "/home/gdevenyi/miniforge3/lib/python3.7/site-packages/brkraw/lib/loader.py", line 16, in load
    return PvDatasetDir(path)
  File "/home/gdevenyi/miniforge3/lib/python3.7/site-packages/brkraw/lib/pvobj.py", line 145, in __init__
    self._parse_info()
  File "/home/gdevenyi/miniforge3/lib/python3.7/site-packages/brkraw/lib/pvobj.py", line 160, in _parse_info
    if len(root.split(os.sep)) == root_path_fregs + 1:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'


```

**Comment by dvm-shlee** [comment]
@gdevenyi tonii_all function is designed to convert multiple Bruker raw data. It may be caused by inputting a single raw directly. Could you try to put your 'raw' into an empty folder and target that parent folder for tonii_all?

**Comment by gdevenyi** [comment]
Putting ``raw`` into a subdirectory ``test`` and using tonii_all:
```
$ brkraw tonii_all test
NoneType: None
Traceback (most recent call last):
  File "/home/gdevenyi/miniforge3/bin/brkraw", line 8, in <module>
    sys.exit(main())
  File "/home/gdevenyi/miniforge3/lib/python3.7/site-packages/brkraw/scripts/brkraw.py", line 157, in main
    raise UnexpectedError
shleeh.errors.UnexpectedError

```

**Comment by dvm-shlee** [comment]
@gdevenyi Thank you for reporting this bug. I found that I made some mistake on the code. The patch will be applied on the next update. Thanks!

**Comment by dvm-shlee** [comment]
@gdevenyi Ok, it will work now from 0.3.3rc6
Please let me know if the issue still exists.
Thank you!

**Comment by gdevenyi** [comment]
Works now. Thanks.
