### ISSUE TITLE
brkraw not working with a dataset

### ISSUE THREAD

**Issue by ycAbout** [BrkRaw/bruker#41]
**Describe the bug**
brkraw works with the example bruker2nifti_qa dataset.
brkraw does not work with another dataset.
Specifically, with another dataset
`brkraw bids_helper <dataset> <outputfile> -j` works, but produced an empty `.xlsx` file within only column names.
`brkraw bids_convert <dataset> <.xlsx> -j <.json> -o <output folder>` does not work, with the following error:

```
  File "/usr/local/bin/brkraw", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/brkraw/scripts/brkraw.py", line 393, in main
    dset = BrukerLoader(dpath)
  File "/usr/local/lib/python3.7/site-packages/brkraw/lib/loader.py", line 89, in __init__
    self._pvobj = load(path)
  File "/usr/local/lib/python3.7/site-packages/brkraw/lib/loader.py", line 17, in load
    return PvDatasetDir(path)
  File "/usr/local/lib/python3.7/site-packages/brkraw/lib/pvobj.py", line 146, in __init__
    self._parse_info()
  File "/usr/local/lib/python3.7/site-packages/brkraw/lib/pvobj.py", line 163, in _parse_info
    if len(root.split(os.sep)) == root_path_fregs + 1:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```
Tried to debug, but not very fruitful. It requires more background information about the project. 
However, this might be helpful: 
for a sub folder containing following files:
`['AdjStatePerScan', 'specpar', 'acqp', 'fid', 'uxnmr.par', 'uxnmr.info', 'method', 'configscan', 'pulseprogram', 'visu_pars']`
The `root_path_fregs` would be `None`, causing 'method' condition `root_path_fregs + 1` error:
```
        for root, subdir, files in os.walk(self.__path):
            if 'subject' in files:
                if root_path_fregs is None:
                    root_path_fregs = len(root.split(os.sep))
                    with open(os.path.join(root, 'subject'), 'r') as f:
                        self._subject = Parameter(f.read().split('\n'))
                else:
                    pass
            elif 'method' in files and 'acqp' in files:
                if len(root.split(os.sep)) == root_path_fregs + 1:
```

cc
@gdevenyi

**Comment by gdevenyi** [comment]
1. I don't think xlsx is valid for an output. It makes csvs.
2. Already reported and fixed in dev, https://github.com/BrkRaw/bruker/issues/27

**Comment by ycAbout** [comment]
> 1. I don't think xlsx is valid for an output. It makes csvs.
> 2. Already reported and fixed in dev, #27

Hi Gabriel,
1. If you follow the documentation here: https://brkraw.github.io/docs/gs_bids.html,  a .xlsx will be produced and it is required for next step. If you mean xlsx should be replaced by csv, I agree. And another json is also an option (I like this one better).
2. Although they seems similar, but they are not the same issue. I simply installed the newest master branch (which already contains the fix of #27), this issue persists.

**Comment by gdevenyi** [comment]
Ugh that is an excel file, it should definitely not be. Please open a separate issue for that.

Based on some more reading here, the .xlsx file needs to be populated to guide the conversion properly. Considering its "empty" bids_convert fails,  although it should throw an error.

**Comment by gdevenyi** [comment]
See https://github.com/BrkRaw/bruker/issues/11 for a workflow of how the helper is used.

**Comment by mabast85** [comment]
Hi,

similar issue here: when trying to convert my own study using tonii_all, I get the same message, i.e.:

$ brkraw tonii_all /Users/matteob/RatScans/20210302_100344_B_B_rat4d_1_1
Traceback (most recent call last):
  File "/Users/matteob/miniconda3/miniconda3/envs/myfslpython603/bin/brkraw", line 8, in <module>
    sys.exit(main())
  File "/Users/matteob/miniconda3/miniconda3/envs/myfslpython603/lib/python3.7/site-packages/brkraw/scripts/brkraw.py", line 184, in main
    study = BrukerLoader(sub_path)
  File "/Users/matteob/miniconda3/miniconda3/envs/myfslpython603/lib/python3.7/site-packages/brkraw/lib/loader.py", line 93, in __init__
    self._pvobj = load(path)
  File "/Users/matteob/miniconda3/miniconda3/envs/myfslpython603/lib/python3.7/site-packages/brkraw/lib/loader.py", line 21, in load
    return PvDatasetDir(path)
  File "/Users/matteob/miniconda3/miniconda3/envs/myfslpython603/lib/python3.7/site-packages/brkraw/lib/pvobj.py", line 145, in __init__
    self._parse_info()
  File "/Users/matteob/miniconda3/miniconda3/envs/myfslpython603/lib/python3.7/site-packages/brkraw/lib/pvobj.py", line 160, in _parse_info
    if len(root.split(os.sep)) == root_path_fregs + 1:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

It does not help if I am in the parent directory or not, the error is the same. Any ideas what may be going wrong?

**Comment by gdevenyi** [comment]
@mabast85 can you please open a seperate issue. Also please share the output of find or tree on the directory you're trying to convert and the version of brkraw you're using.
