### ISSUE TITLE
tonii_all fails with cryptic error if run on single dataset

### ISSUE THREAD

**Issue by mabast85** [BrkRaw/bruker#43]
Hi,

I am having an issue when trying to convert my own study using tonii_all.
I get the following message:

$ brkraw tonii_all /Users/matteob/RatScans/20210302_100344_B_B_rat4d_1_1
Traceback (most recent call last):
File "/Users/matteob/miniconda3/miniconda3/envs/myfslpython603/bin/brkraw", line 8, in 
sys.exit(main())
File "/Users/matteob/miniconda3/miniconda3/envs/myfslpython603/lib/python3.7/site-packages/brkraw/scripts/brkraw.py", line 184, in main
study = BrukerLoader(sub_path)
File "/Users/matteob/miniconda3/miniconda3/envs/myfslpython603/lib/python3.7/site-packages/brkraw/lib/loader.py", line 93, in init
self._pvobj = load(path)
File "/Users/matteob/miniconda3/miniconda3/envs/myfslpython603/lib/python3.7/site-packages/brkraw/lib/loader.py", line 21, in load
return PvDatasetDir(path)
File "/Users/matteob/miniconda3/miniconda3/envs/myfslpython603/lib/python3.7/site-packages/brkraw/lib/pvobj.py", line 145, in init
self._parse_info()
File "/Users/matteob/miniconda3/miniconda3/envs/myfslpython603/lib/python3.7/site-packages/brkraw/lib/pvobj.py", line 160, in _parse_info
if len(root.split(os.sep)) == root_path_fregs + 1:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

It does not help if I am in the parent directory or not, the error is the same. Any ideas what may be going wrong?

In the 20210302_100344_B_B_rat4d_1_1 folder I have the structure shown in the two attached images.
I am using brkraw version 0.3.6

<img width="1004" alt="Screenshot 2021-03-05 at 13 29 42" src="https://user-images.githubusercontent.com/44471478/110121884-db32ee00-7db6-11eb-9e85-05b4431a0062.png">
<img width="1007" alt="Screenshot 2021-03-05 at 13 30 00" src="https://user-images.githubusercontent.com/44471478/110121923-e4bc5600-7db6-11eb-9864-46472864083e.png">

**Comment by gdevenyi** [comment]
This has already been brought up before by me, though it needs to be fixed, tonii_all is intended to be used on a directory which `contains` directories which contain bruker datasets.

https://github.com/BrkRaw/bruker/issues/2#issuecomment-636521168

If you intend to convert one dataset, use tonii.

Please change title to "tonii_all fails with cryptic error if run on single dataset"

**Comment by mabast85** [comment]
Thanks very much for your help, it worked on the parent directory using the tonii option.
I changed the title for your record.

Just noticed a typo as well while running the conversion:
"NifTi file is **genetared**..."

**Comment by ycAbout** [comment]
Hi @mabast85 , where do you find brkraw version 0.3.6? the newest released one is v 0.3.4?

**Comment by gdevenyi** [comment]
> Hi @mabast85 , where do you find brkraw version 0.3.6? the newest released one is v 0.3.4?

https://github.com/BrkRaw/bruker/blob/master/brkraw/__init__.py#L3
