### ISSUE TITLE
Conversion of T1w FLASH with 2 repetitions crashing

### ISSUE THREAD

**Issue by egarza** [BrkRaw/bruker#6]
Hi,

I'm using a Bruker Pharmascan.
brkraw v0.3.3rc5
Ubuntu 18 LTS

When I try to convert my 3D_Flash image with 2 repetitions (2 3D volumes) with the GUI, it doesn't let me:

INFO:

```
Paravision 6.0.1
----------------
UserAccount:	nmrsu
Date:		2019-11-07
Researcher:	Pilot_001
Subject ID:	B03GarzaAlcohol_I2BA_Adol_001
Session ID:	B03GarzaAlcohol_I2BA_Adol_001
Study ID:	1
Date of Birth:	25 Sep 2019
Sex:		male
Weight:		0.201 kg
Subject Type:	Quadruped
Position:	Prone		Entry:	HeadFirst

[ScanID]	Sequence::Protocol::[Parameters]
[001]	Bruker:FLASH::1_Localizer::
	[ TR: 100 ms, TE: 2.50 ms, pixelBW: 159.22 Hz, FlipAngle: 30 degree]
    [01] dim: 2D, matrix_size: 256 x 256 x 3, fov_size: 50 x 50 (unit:mm)
         spatial_resol: 0.195 x 0.195 x 2.000 (unit:mm), temporal_resol: 12800.000 (unit:msec)
[002]	Bruker:FLASH::3D_FLASH_Mn_Garza::
	[ TR: 30.76 ms, TE: 5 ms, pixelBW: 173.61 Hz, FlipAngle: 10 degree]
    [01] dim: 3D, matrix_size: 120 x 160 x 160 x 2, fov_size: 19.0976 x 25.6 x 25.6 (unit:mm)
         spatial_resol: 0.159 x 0.160 x 0.160 (unit:mm), temporal_resol: 694035.840 (unit:msec)
[003]	Bruker:FLASH::1_Localizer::
	[ TR: 100 ms, TE: 2.50 ms, pixelBW: 159.22 Hz, FlipAngle: 30 degree]
    [01] dim: 2D, matrix_size: 256 x 256 x 3, fov_size: 50 x 50 (unit:mm)
         spatial_resol: 0.195 x 0.195 x 2.000 (unit:mm), temporal_resol: 12800.000 (unit:msec)
[004]	Bruker:EPI::SE_EPI_sat::
	[ TR: 2100 ms, TE: 19 ms, pixelBW: 4006.41 Hz, FlipAngle: 90 degree]
    [01] dim: 2D, matrix_size: 72 x 64 x 42 x 300, fov_size: 18 x 16 (unit:mm)
         spatial_resol: 0.250 x 0.250 x 0.550 (unit:mm), temporal_resol: 2100.000 (unit:msec)
[005]	Bruker:FieldMap::B0Map-ADJ_B0MAP::
	[ TR: 20 ms, TE: 0 ms, pixelBW: 1860.12 Hz, FlipAngle: 30 degree]
    [01] dim: 3D, matrix_size: 64 x 64 x 64, fov_size: 45 x 45 x 45 (unit:mm)
         spatial_resol: 0.703 x 0.703 x 0.703 (unit:mm), temporal_resol: 81920.000 (unit:msec)
[006]	Bruker:RARE::T2_TurboRARE::
	[ TR: 4212.78 ms, TE: 33 ms, pixelBW: 140.85 Hz, FlipAngle: 90 degree]
    [01] dim: 2D, matrix_size: 256 x 256 x 24, fov_size: 30 x 30 (unit:mm)
         spatial_resol: 0.117 x 0.117 x 1.200 (unit:mm), temporal_resol: 269617.981 (unit:msec)
```

[https://ibb.co/GTSxJWf](Image)

```
NoneType: None
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/egarza/.local/lib/python3.6/site-packages/brkraw/ui/main_win.py", line 185, in _save_as
    self._raw.save_as(self._scan_id, self._reco_id, filename, dir=self._output)
  File "/home/egarza/.local/lib/python3.6/site-packages/brkraw/lib/loader.py", line 394, in save_nifti
    niiobj = self.get_niftiobj(scan_id, reco_id, crop=crop)
  File "/home/egarza/.local/lib/python3.6/site-packages/brkraw/lib/loader.py", line 269, in get_niftiobj
    imgobj = self.get_dataobj(scan_id, reco_id, slope=slope)
  File "/home/egarza/.local/lib/python3.6/site-packages/brkraw/lib/loader.py", line 214, in get_dataobj
    raise UnexpectedError(message='Unexpected frame group combination;'
shleeh.errors.UnexpectedError
```
I also can't see the Image preview in the GUI.

The rest of the sequences were exported fine.

Thank you,

Eduardo

**Comment by dvm-shlee** [comment]
@egarza Hi! Thank you for reporting the bug.
Could you share with me the image having the issue? Zip compressed file would be the best for me to test.

**Comment by egarza** [comment]
Sure, here is the sequence file:

[https://drive.google.com/file/d/1L7c1W7_a7_JzPO_WuW8xt4pvN99o3aPQ/view?usp=sharing](Bruker File)

**Comment by dvm-shlee** [comment]
I just requested the access with my google id jaru419@gmail.com

**Comment by egarza** [comment]
its the folder of the sequence, with the pdata file inside. 

Sorry, I thought it was shared with anyone with the link. 

Here it is again: [https://drive.google.com/file/d/1L7c1W7_a7_JzPO_WuW8xt4pvN99o3aPQ/view?usp=sharing](ZIP)

**Comment by dvm-shlee** [comment]
@egarza Ok! it seems working now. Could you try a new version, 0.3.3rc6?

**Comment by egarza** [comment]
great, thanks, let me do that.

**Comment by egarza** [comment]
It worked, great, thank you very much!
